### ISSUE TITLE
The problem of adding to HA

### ISSUE THREAD

**Issue by Xach-s-usami** [DanteWinters/lux-power-distribution-card#23]
I followed the instructions, but when adding it, it says in the panel that the card was not found (I attach a screenshot)
Tried through it HACH did not help, the same thing writes that it is not available
![Screenshot_2](https://github.com/DanteWinters/lux-power-distribution-card/assets/114307703/756943c6-d2b9-4268-8f37-77ef1681c4a5)
![Screenshot_3](https://github.com/DanteWinters/lux-power-distribution-card/assets/114307703/764a00d4-fc75-4120-8c60-eadd4fc54ec1)

**Comment by DanteWinters** [comment]
I think you manual resource is wrong. It has backslashes in the front and forward-slashes later on in the path.
Remove it and just rely on the HACS path and see if that fixes it.

**Comment by DanteWinters** [comment]
@Xach-s-usami  have you been able to resolve the issue?

**Comment by Xach-s-usami** [comment]
> @Xach-s-usami  have you been able to resolve the issue?

No, I'm still puzzling over how to solve this case, I deleted everything and did it in stages

**Comment by Pieterjvr** [comment]
@Xach-s-usami , It seems like from time to time HACS frontend stop to load. What I have done is to copy the card out and directly under /config/www/ and added it manual.

/local/lux-power-distribution-card.js

![image](https://github.com/DanteWinters/lux-power-distribution-card/assets/37001337/d15b7352-0ef4-49b7-8a6e-3a2270207343)

**Comment by Xach-s-usami** [comment]
thank you for your help, the problem turned out to be that my sensors are registered with a serial number (but this is not accurate)
I deleted everything, cleared the cache, and then reloaded via Hass
And began to manually write the lines
and I got it all thanks for the help)))
I sit and admire
![Uploading Screenshot_5.png…]()

**Comment by Xach-s-usami** [comment]
thank you for your help, the problem turned out to be that my sensors are registered with a serial number (but this is not accurate)
I deleted everything, cleared the cache, and then reloaded via Hass
And began to manually write the lines
and I got it all thanks for the help)))
I sit and admire
![Screenshot_5](https://github.com/DanteWinters/lux-power-distribution-card/assets/114307703/8d95dc2a-baeb-4fbb-90e0-2b67b9f789c4)
