### ISSUE TITLE
"undefined is not an object"

### ISSUE THREAD

**Issue by mikekenyon99** [DanteWinters/lux-power-distribution-card#37]
Hi,

I have installed this and Im getting this error when adding it to my dashboard.  I have changed the BAxxxx to match my installation but I cannot get this error to disappear.  

<img width="498" alt="Screenshot 2023-09-27 at 22 21 16" src="https://github.com/DanteWinters/lux-power-distribution-card/assets/42475982/05b90a27-d927-4563-bbac-25a1910cf39e">

Any ideas on how to get this working?

Mike

**Comment by DanteWinters** [comment]
Hi, please provide the full config. You can change the inverter serial number to protect private info

**Comment by mikekenyon99** [comment]
Hi - I rebooted HA and it started working. 

Mike
