### ISSUE TITLE
iOS HA app not showing power card

### ISSUE THREAD

**Issue by Aussie75** [DanteWinters/lux-power-distribution-card#60]
This use to work, though not exactly sure when it stopped, though the error in the app is showing undefined is not an object (evaluating 'this._config.generator_power.is_used')

from the log

2024-08-12 12:46:54.614 ERROR (MainThread) [frontend.js.latest.202407100] Uncaught error from WebKit 605.1.15 on iOS 17.5.1
TypeError: undefined is not an object (evaluating 'this._config.generator_power.is_used')
updateGrid (/hacsfiles/lux-power-distribution-card/lux-power-distribution-card.js:357:49)
updateCard (/hacsfiles/lux-power-distribution-card/lux-power-distribution-card.js:79:22)
hass (/hacsfiles/lux-power-distribution-card/lux-power-distribution-card.js:21:20)
createCardElement (src/panels/lovelace/cards/hui-card.ts:101:20)
ev.stopPropagation (src/panels/lovelace/cards/hui-card.ts:127:26)
dispatchEvent ([native code]::)
event (src/common/dom/fire_event.ts:76:21)
tag.includes (src/panels/lovelace/create-element/create-element-base.ts:136:14)

**Comment by DanteWinters** [comment]
Please check out issue #61 . This is a common issue after updating, so I opened a bug that I'll leave open specifically for that.
